name: deploy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'
          cache: npm
          scope: '@MeigetsuID'
      - name: Ready to run
        run: |
          npm ci
      - name: Execute Test
        run: |
          npm run ci
  publish:
    runs-on: ubuntu-22.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'
          cache: npm
          scope: '@MeigetsuID'
      - name: Ready to run
        run: npm ci
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
